### PR TITLE
Multiple Drive Modes for Hovercar variant

### PR DESCRIPTION
**Pull request by Guruth**
Hey, 

I've implemented a multi mode drive selection for the hovercar variant, similar to [Larsm bbycar](https://github.com/larsmm/hoverboard-firmware-hack-FOC-bbcar).

The limits are defined in config.h:
- Mode 0 == Kid Mode - Slow accelleration and speed
- Mode 1 == Adult Mode (Default) - Medium accellleration and speed
- Mode 2 == Fun Mode - Default accelleration and max speed

The modes are selected by pressing the throttle or break trigger when starting the bobbycar. Mode 1 is selected if no trigger is pressed.
To prevent a sudden jump forward, I've added a loop that waits until all triggers are returned to ther minimum position.  

Code cleanup hints are more than welcome.

### CODE REVIEW

**Comment by EFeru** [comment]
Nice @Guruth! Thank you for your contribution. I hope to find some time next week to check it and merge.

**Comment by fluppie** [comment]
Hi, is it possible that it works inverted? Pressing brake on boot = fast mode and pressing throttle = slow mode.

**Comment by Guruth** [comment]
Hey @fluppie,
Yes, thats fairly simple. 
You can just switch the predefined values in Inc/config.h (529 - 538):
```
  #ifdef MULTI_MODE_DRIVE
      #define MULTI_MODE_DRIVE_M1_MAX   1000
      #define MULTI_MODE_DRIVE_M1_RATE  450

      #define MULTI_MODE_DRIVE_M2_MAX   500
      #define MULTI_MODE_DRIVE_M2_RATE  300

      #define MULTI_MODE_DRIVE_M3_MAX   175
      #define MULTI_MODE_DRIVE_M3_RATE  175
  #endif
```

**Comment by lsls5921** [comment]
@Guruth @EFeru Hello, how can I choose the mode? I can't choose the mode after downloading the program to the hover board. How can I change it? Can you help me

**Pull request merged**
