### PR TITLE
Fixes and improvements

### PR DESCRIPTION
**Pull request by Candas1**
- New forms for issues with fields and drop-down lists.
- Debug messages at startup displaying limits, and if coming from config.h or from EEprom
- Debug messages explaining why the board is powering off (temperature alert, battery low, inactivity, button press)
- Rejecting autocalibration if both inputs are disabled
- BAT_DEAD_ENABLE parameter not to power off if battery is low, can help debug the battery calibration
- Only disable motors when on/off button is pressed for more than 80ms, to prevent disabling motor if on/off button is pressed because of vibrations while driving
- inactivity counter not ticking while using cruise control, except if target is really small
- Tank_steering parameter, basically it's skipping the mixing of speed and steer
- When cruise_control_support is enabled and sideboard input is active, it replaces field_weakening
- Possibility to use control_usart/sideboard_usart with debug_usart (was failing before because of ptr variable was used twice )
- Debug protocol is skipping the command if not starting with $ character. This allows to send commands with debug protocol even when CONTROL_SERIAL_USART or SIDEBOARD_SERIAL_USART are used. The firmware either picks the ascii command or the binary frame
- Checking if only one wheel is enabled when calculating **speedavg**

### CODE REVIEW

**Comment by EFeru** [comment]
Wow, those are quite some improvements. I will take a look soon. Thanks Candas!

**Comment by Candas1** [comment]
Thanks Emanuel.
While browsing the code and thinking, I found out about 2 details I might have missed actually:
- [here](https://github.com/Candas1/hoverboard-firmware-hack-FOC/blob/29535a26e67bac30b05edd1244414c8d01f78524/Src/main.c#L539) I forgot about standstill hold
- [here](https://github.com/Candas1/hoverboard-firmware-hack-FOC/blob/29535a26e67bac30b05edd1244414c8d01f78524/Src/main.c#L523) if using tank_steering, it will beep when going backwards only for the right wheel, as speed variable will map to cmdR. Checking speedavg might be enough, I need to try it this evening

**Comment by Candas1** [comment]
ok, now I am checking if STANDSTILL_HOLD is active.
And actually speed variable is checked not to have backward beeps when pushing the vehicle back manually.
I replaced it by cmdR and cmdL.

**Comment by EFeru** [comment]
Checked and from my side it all looks good. Again nice improvements! Thanks!

**Pull request merged**
