### PR TITLE
added bobby car code

### PR DESCRIPTION
**Pull request by asdfa9527**
你好

### CODE REVIEW

**Comment by EFeru** [comment]
@asdfa9527 Thank you for your contribution.
- Apparently there are some conflicts, can you resolve them?
- And I saw you updated the ReadMe with bobby car description. Can you keep only content similar to other variants and move the detailed description to a new Wiki page in Variants -> BBCAR?
(You should be able to edit the wiki because I allowed editing until this PR is finished).

**Comment by EFeru** [comment]
Hi @asdfa9527 @larsmm ,

I tried merging the `main` branch into this PR and also resolved the conflicts. However, I am not able to push (see below), any idea? (it is the first time I encounted this).
image

**Comment by larsmm** [comment]
Hi Emanuel,
my fork was not meant to be merged into your repo in this way. I changed quite a lot of things that are not compatible with your standard settings. It only works with this specific settings for CTRL_TYP_SEL, FIELD_WEAK_LO/HI for example. They should be added to the VARIANT_BBCAR section in config.h. My code is not so pretty in some places: "void beepShortMany2" is not a good name for example. I commented out your timeout safety code and made my own. I put "# " before every debug printf. So it is easyer to machine-read the output. I do not now if you want that. There is also a bug in the backward beeping. You changed quite a lot of things since my last pull. I think I should revise my code before doing a pull request. Can I see your resolved-conflicts-version somewhere? That would help me to rework my code.

You are trying to write to my repo. If I had made the pull request, you probably could have merged it.

I renamed master branch to main a few minutes ago. Now the pull request sais "larsmm deleted the master branch...".

@asdfa9527: It would have been nice to ask me before doing the pull request.

**Comment by EFeru** [comment]
> Can I see your resolved-conflicts-version somewhere? That would help me to rework my code.

If I could push then you could take over and refine. I can try one more time now.

**Comment by larsmm** [comment]
Lets close this pull request. Maybe I will create one myself in the feature.

**Comment by EFeru** [comment]
Closed for now. @larsmm if you wish, feel free to make a new PR.

**Pull request closed without merging**
